# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [ ]:
import numpy as np

arr = np.random.randint(1,20,size=(5,5))   
print("Original Array:")
print(arr)

arr[:,2] = 1      # replacing the value in the 3rd coloumn with 1
print("Modified Array:")
print(arr)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

np.fill_diagonal(arr2, 0)
print("Modified array:")
print(arr2)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [ ]:
arr = np.arange(1,37).reshape(6,6)
print("Original Array:")
print(arr)

sub_array = arr[2:5][1:4]
print("Extracted Array")
print(sub_array)

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
arr = np.random.randint(1,20,size=(5,5))

print("Array")
print(arr)

border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print('border_elements')
print(border_elements)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
ar1 = np.random.randint(1,21,size=(3,4))

ar2 = np.random.randint(1,21,size=(3,4))
print("ADD")
print(ar1+ar2)
print("Subs")
print(ar1-ar2)
print('Multiply')
print(ar1*ar2)
print('Divide')
print(ar1/ar2)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
ar1 = np.arange(1,17).reshape(4,4)
print(ar1)

row_sum = np.sum(ar1,axis=1)    # axis=1 for row wise
coloumn_sum = np.sum(ar1,axis=0) # axis = 0 for coloumn wise

print(row_sum)
print(coloumn_sum)

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [ ]:
import numpy as np
ar1 = np.random.randint(1,21,size=(5,5))


mean = np.mean(ar1)
median = np.median(ar1)
standard_deviation = np.std(ar1)
variance = np.var(ar1)


print('Mean',mean)
print('Median',median)
print('Std Dev',standard_deviation)
print('Variance',variance)

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
import numpy as np

ar1 = np.arange(1,10).reshape(3,3)

print(ar1)

mean = np.mean(ar1)
std_dev = np.std(ar1)
normalized_array = (ar1-mean)/std_dev   # nomalized array formula


print(normalized_array)

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
ar1 = np.random.randint(1,22,size=(3,3))
print(ar1)

ar2 = np.random.randint(1,12,size=(3,))

print(ar2)

add = ar1 + ar2

print(add)

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
ar1 = np.random.randint(1,21,size=(4,4))
ar2 = np.random.randint(1,21,size=(4,))

subs = ar2-ar1
print(subs)


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [ ]:
ar1 = np.random.randint(1,22,size=(3,3))

print(ar1)

determinent = np.linalg.det(ar1)
print(determinent)

inverse = np.linalg.inv(ar1)
print(inverse)

eigenvalues = np.linalg.eig(ar1)
print(eigenvalues)

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
arr1 = np.random.randint(1,10,size=(2,3))
arr2 = np.random.randint(1,10,size=(3,2))

multiply = np.dot(arr1,arr2)

print(multiply)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)

arr2 = arr1.reshape(1,9)

arr3= arr2.reshape(9,1)


print(arr1)
print(arr2)
print(arr3)

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [ ]:
arr1 = np.random.randint(1,20,size=(5,5))
print(arr1)

flatten_array = arr1.flatten()
print(flatten_array)

arr2 = flatten_array.reshape(5,5)
print(arr2)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)

corners = arr1[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [ ]:
arr1 = np.random.randint(1,20,size=(4,4))
print(arr1)

arr1[arr1 > 10] = 10
print("Modified array:")
print(arr1)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]

arr = np.array([('Alice',32,67.2),('Price',46,44.4),('Apoorv',28,55.2)],dtype=data_type)
print(arr)


## sorted

sorted_data = np.sort(arr,order='age')

print(sorted_data)

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
data_type = [('x','i4'),('y','i4')]

data = np.array([(2,4),(4,5),(7,8)],dtype=data_type)

print(data)

# euclidien distance 

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [ ]:
import numpy.ma as ma
arr1 = np.random.randint(1,20,size=(4,4))

print(arr1)

masked_array = ma.masked_greater(arr1,10)
print(masked_array)

sum_masked = masked_array.sum()

print(sum_masked)

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [123]:
# Create a masked array of shape (3, 3) with random integers
arr = np.random.randint(1, 21, size=(3, 3))
masked = ma.masked_array(arr, mask=np.eye(3, dtype=bool))
print("Original array:")
print(arr)
print("Masked array:")
print(masked)

# Replace the masked elements with the mean of the unmasked elements

# Compute the mean of the unmasked elements
mean_unmasked = masked_array.mean()

# Replace masked values with the mean
filled_array = masked_array.filled(mean_unmasked)

print(filled_array)


Original array:
[[20  8  2]
 [18 19  4]
 [15 13 16]]
Masked array:
[[-- 8 2]
 [18 -- 4]
 [15 13 --]]
[[11 14  3]
 [ 6 11  7]
 [19 20 11]]
